# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy source
COPY . .

# Build TypeScript
RUN npm run build

# Expose no ports; uses stdio

# Default command
ENTRYPOINT ["node", "cli.js"]
